### ISSUE TITLE
Update Packagist to 1.0.2

### ISSUE THREAD

**Issue by mikeselander** [humanmade/Mercator#100]
Currently, 1.0.1 is the latest version available on Packagist for Mercator. We should update this to 1.0.2 to make it available as well.

**Comment by rmccue** [comment]
Hmm, Packagist just uses the tags from GitHub so there must be something wrong with the sync, as [we have a 1.0.2 release](https://github.com/humanmade/Mercator/releases/tag/1.0.2).

**Comment by mikeselander** [comment]
🤔 OK, I'll take a look next week maybe.

**Comment by rmccue** [comment]
I tried the manual "update" on the Packagist page and no luck, so not sure what's going on. Could be an issue with the license value, as I've seen that mess up a bit recently.
