### ISSUE TITLE
v2 is dead?

### ISSUE THREAD

**Issue by cfoellmann** [humanmade/Mercator#102]
I know your resources might be used elsewhere. Is the split version (v2!?) dead? I was trying to wait for it but if you guys say you stick with the structure of 1.x I would to an stop looking at the "new" stuff.

Cheers

**Comment by roborourke** [comment]
It is definitely a resourcing issue. v2 isn't dead, I think I was waiting for a few of the other pieces to fall into place, specifically #89 before I made the switch.

I also have a bit of outstanding work to do on the GUI repo to update the network level admin. Automatic checks for DNS propagation was on the list there too but it's a bit more work.

Anyway, it's my fault it's been hanging round so long. Will start by adding the other plugins to packagist today then work out how much time I need to complete the GUI.

**Comment by cfoellmann** [comment]
It is great to hear that!

I would love to help. Please comment on my issues/PRs so I can refresh, close or whatever.
If you open issues with stuff that is to be done I will certainly try to pitch in.

**Comment by roborourke** [comment]
@cfoellmann that'll be a huge help thanks! I'll go through those other repos and make sure they're up to date.

**Comment by JulienMelissas** [comment]
Hey there! Just wondering if there is any movement on this, or if someone is using 2.0 in production? We ran into issues using 1.0 but I think we could use 2.0 if we didn't have the SSO component...
