### ISSUE TITLE
Fixing "ERROR: Cookies are blocked or not supported by your browser." error with Mercator

### ISSUE THREAD

**Issue by marcelturi** [humanmade/Mercator#103]
(Sorry, probably more support than issue)

A common problem encountered when using a domain mapping plugin for WordPress is receiving the following error when trying to log into WordPress on a mapped domain.

> ERROR: Cookies are blocked or not supported by your browser. You must enable cookies to use WordPress.

When not using Mercator in the past, I would use a combination of the following `wp-config.php`

    define('COOKIE_DOMAIN', '');
    define('ADMIN_COOKIE_PATH', '/');
    define('COOKIEPATH', '/');
    define('SITECOOKIEPATH', '/');
    define('COOKIEHASH', 'example');

However, I've tried resolving this issue with Mercator handling domain mapping using a combination of those settings (`COOKIE_DOMAIN` definitely can't be used) but am still unable to log into a mapped domain because of this cookie error. To note in my circumstance, I can log into the primary domain just fine.

Any tips?

**Comment by marcelturi** [comment]
OK, resolved with `define('COOKIE_DOMAIN', false);` so feel free to mark issue as fixed.

**Comment by rmccue** [comment]
FWIW, you should also be able to get away with not defining any of those constants except `COOKIEHASH`, as WordPress can dynamically define them instead.

**Comment by splaquet** [comment]
funny... the solution @marcelturi provided worked for me as well.  i had to insert those //disable lines before the closing line, but it worked.

anyone know what type of adverse effect that this might have?

**Comment by rmccue** [comment]
It'll disable cross-domain single sign-on.
