### ISSUE TITLE
what happened to domain alias with wordress 4.9.8

### ISSUE THREAD

**Issue by chicco785** [humanmade/Mercator#104]
we can't add / edit domain aliases anymore :(

**Comment by mrjarbenne** [comment]
I still can on my install, running 4.9.8. Perhaps another plugin is conflicting with Mercator on your site?

**Comment by rmccue** [comment]
Hi, we'd be happy to assist in debugging if you discover the problem is within Mercator, but otherwise per [our support policy](https://engineering.hmn.md/projects/support/), we cannot offer general support.
