### ISSUE TITLE
Unable to install the Mercator on wordpress

### ISSUE THREAD

**Issue by shijiezhou1** [humanmade/Mercator#123]
Installing plugin from uploaded file: Mercator-1.0.3.zip
Unpacking the package…

Installing the plugin…

The package could not be installed. No valid plugins were found.

Plugin installation failed.

Go to Plugin Installer

![image](https://user-images.githubusercontent.com/28111591/111400995-68edd200-8703-11eb-8a4a-381a4e5b3e92.png)

Tried to upload the zip and it doesn't work at all

**Comment by mrjarbenne** [comment]
Check out the Readme file in the repo. Mercator is installed differently than traditional plugins.

**Comment by rmccue** [comment]
This is not a bug, please read the installation instructions.
