### ISSUE TITLE
Alias tab not active 

### ISSUE THREAD

**Issue by spacedmonkey** [humanmade/Mercator#24]
When editing a site alias, the alias tab, in not active. 

See screenshot. 

![screen shot 2014-12-04 at 22 32 53](https://cloud.githubusercontent.com/assets/237508/5307594/3424e1d0-7c06-11e4-8019-a232a5e5533e.png)

**Comment by johnjamesjacoby** [comment]
This looks resolved to me:

![screen shot 2016-01-27 at 1 13 26 pm](https://cloud.githubusercontent.com/assets/88951/12625098/ce85883e-c4f7-11e5-9ccf-03e9fd087f53.png)

**Comment by roborourke** [comment]
Thanks chaps, porting over to https://github.com/humanmade/Mercator-GUI/issues/4

Can hopefully be fixed at the same time.
