### ISSUE TITLE
Setting primary domain

### ISSUE THREAD

**Issue by davisshaver** [humanmade/Mercator#3]
Have you thought about allowing a primary domain to be set? This is a major feature of the existing solution and seems like it'd be useful to incorporate into Mercator as well.

**Comment by mrjarbenne** [comment]
>Is there a use case for having all domains redirect to the primary one? For my own use cases, I'd like to >have all mapped domains redirect to the primary but with exceptions (the original subdomain, in my >case). Are there any other use cases we need to handle here?

+1 for this. If we look at how wordpress.com handles this. For the most part aliases map over to the primary domain, except in cases where you are accessing the dashboard. In an SSL context on multisite, where the subdomain is protected by a wildcard certificate, but the mapped domains may not have individual certificates, redirecting back to the unmapped domain on login and admin calls solves the "unsafe content ahead" errors in the browser when logged in users are attempting to manage their site; but ensures the audience is always taken to the mapped domain, rather than the unmapped subdomain.

**Comment by robneu** [comment]
+1 for adding the option to 301 all aliases to a single "canonical" domain.

**Comment by thatryan** [comment]
Chiming in as I **think** this is referencing an issue we have run into as well. Would adding this option in take care of the sites having "duplicate" content once *live*, meaning once a domain is mapped, or aliases, then the original subdomain the site was built on would no longer be used and redirect to the mapped domain?

**Comment by mrjarbenne** [comment]
"Duplicate content" probably isn't the right way to describe it. There is only one instance of the content (posts, pages, etc).

Think of it more like two doors to the same house. Once you are in the house, it's all the same. 

One door (the mapped domain) is well lit, with a beautiful garden, and welcoming awning. 

The other door (the unmapped domain) is ugly, still has the contractors name on it, and there's building material stacked around the entrance.

Right now people come in both doors and we can't control the traffic.

We need a bouncer who forces everyone to the first door: "move along, nothing to see here at this ugly back door".

**Comment by robneu** [comment]
For the record, this is a duplicate content issue in SEO terms. If nothing exists to reference the single canonical resource, you will have indexation problems. Using the `rel="canonical"` tag does help with this, but it's not really a reliable solution 100% of the time. The ideal situation is that there is a single copy of the content and any potential "duplicates" are 301'd to that version.

A big part of why this is an issue is that links in serialized content, such as widgets or certain custom fields, will never get updated by default. To replace all instances of them you would need to use either an automated script via WP CLI or a tool like [this](https://interconnectit.com/products/search-and-replace-for-wordpress-databases/). 

When you have both duplicate copies of a site AND links to said copies, then you can wind up causing yourself some pretty serious SEO problems. This is especially true if for some reason the root domain of the network gets penalized or de-indexed for some reason. If that happens, all the sites on the network with links pointing to and originating from the root domain can be negatively affected.

**Comment by mrjarbenne** [comment]
Ahhh. That makes sense, and suddenly adds a greater sense of urgency. I hadn't looked at it that way before.

**Comment by thatryan** [comment]
Yea what Rob said. Google indexes all the subdomain "staging site" urls and sees hundreds of them in same subdomain on multisite install, all sites in same niche market as well so we are slammed lol

I have been running wp-cli search replace recursive to change all subdomain a to mapped domain once "live" but that gets cumbersome, especially iterating over several hundred sites to do it...

**Comment by thatryan** [comment]
Do we think this is something that will be addressed soon?

**Comment by scarstens** [comment]
I think I'm going to look into this today. My goal is simple here, which is to simply hook into the template_redirect action and check if you are visiting a domain that has a "mapped alias set" and redirect you (301) to the alias thats active. This will resolve 2 things:
1. Resolve SEO issues related to dupe content of allowing the old subdomain to load.
2. Resolve the My-Sites dropdown which currently links to the subdomains, by redirecting them to the proper dashboard url. (they will still appear to be wrong links, but I spent a long time trying to fix that, and no solutions exist that work in scale ie 300+ sites in the multisite).

**Comment by scarstens** [comment]
also noting its an issue on this endpoint, which lists "my sites" with bad links to subsites instead of aliases.
http://samplemu.dev/wp-admin/my-sites.php

**Comment by thatryan** [comment]
Any luck @scarstens ? Would love to move back to Mercator, I have a new network to setup which needs to be all https and the current mapping plugin wont do that very well.

**Comment by scarstens** [comment]
@thatryan I only partially solved the problem (just enough that we could use mercator on our local VVV installs). you are welcome to chat me on WordPress core slack and I can tell you where we are at exactly. Also none of my PR's have been handled here, so all my updates are only available at https://github.com/fansided/Mercator

**Comment by roborourke** [comment]
@davisshaver so we opted to use WPs built in handling for setting the primary domain, that is to set the `site_url` to the primary domain and the subdomain as an alias.

The `Mapping` object now has a method `make_primary()` which switches the two by updating `site_url`, removing the alias then adding a new one with the previous `site_url` value.

Front end redirection issues we can handle in https://github.com/humanmade/Mercator-Redirect

https://github.com/humanmade/Mercator-Redirect/issues/2
