### ISSUE TITLE
Domain setting per site

### ISSUE THREAD

**Issue by nattyait** [humanmade/Mercator#46]
Do you have any plan to implement Domain Setting per site? or do you want contributor?

Natty

**Comment by ericandrewlewis** [comment]
Hi @nattyait, what do you mean by "Domain Setting per site"?

**Comment by alexphelps** [comment]
@ericandrewlewis I believe she means a per site setting page similar to MU Domain Mapping like below. 

![image](https://cloud.githubusercontent.com/assets/674282/9843540/71b4a512-5ae5-11e5-86c9-52b5e628432b.png)

**Comment by scarstens** [comment]
+1 here, if separate admins are responsible for the sub-sites, you can't rely on these settings being in the network settings area. @nattyait yes please pass through your contribution if you know how to build this properly for mercator!

**Comment by Wemago** [comment]
+1 for this. I'm really missing this one.

**Comment by roborourke** [comment]
@scarstens @Wemago @nattyait - previously Mercator was built as a basis for others to build this kind of feature on top of however in the upcoming v2 there will be a per site admin that you can enable via `sunrise.php`:

Follow development here https://github.com/humanmade/Mercator-GUI
