### ISSUE TITLE
How does this plugin work?

### ISSUE THREAD

**Issue by chapeauvert** [humanmade/Mercator#53]
Hi,

I am taking a chance with this plugin since I am having major issues with WPMU Domain Mapping.

I followed the installation instructions, but now have now idea how to map my domains.

Any help would be greatly appreciated.

**Comment by ericandrewlewis** [comment]
Hi @chapeauvert. If you've already installed Mercator, then you can map domains (or make "aliases," the  term Mercator uses) under the Network Admin > Sites > Edit Site screen.

**Comment by ericandrewlewis** [comment]
I've added more steps to the installation process and about how domain mapping works with Mercator. I'm going to close this out as hopefully that helps describe how to use Mercator. If not feel free to re-open with more specific issues.
