### ISSUE TITLE
Can the Mercator be use to work with VVV on local?

### ISSUE THREAD

**Issue by ghost** [humanmade/Mercator#65]
Hi! I try to use the Mercator with VVV on Mac. I set my /etc/hosts file to 192.168.50.4 (vvv) but then i get kicked back to vvv.dev. I have sunrise.php and aliases are set properly.

192.168.50.4 vvv.dev
192.168.50.4 site1.dev (primary site works fine)
192.168.50.4 site2.dev

Enter "site2.dev" in browser => vvv.dev :(

Thanks for help

**Comment by soderlind** [comment]
In your `VVV/config/nginx-config/sites/site1.conf`, add site2.dev to `server_name`:

```log
server_name  site1.dev site2.dev
```

You (might) have to do a `vagrant reload --provision` afterwards

**Comment by pbredenberg** [comment]
👍 
I confirmed this works. Make sure if you're just adding a new site that you assign yourself as a user and add some content to avoid a few moments of confusion.

**Comment by roborourke** [comment]
I think we need to improve the docs significantly. Will add this advice for common development environment setups such as VVV. Thanks for the responses @soderlind @pbredenberg
