### ISSUE TITLE
Disable multi login

### ISSUE THREAD

**Issue by beatelite** [humanmade/Mercator#69]
I noticed the docs said 

> _"Internally, Mercator looks at a request's domain and informs WordPress what set of tables to use. User authentication cookies are set for all domains in the network, so a user logs in on one site and is authenticated across all."_

Is there any way to disable this? I don't want users being authenticated to any other site on the network unless explicitly set by the admin of that subsite.

**Comment by mrjarbenne** [comment]
You can accomplish this by disabling SSO (Single Sign On). The @fansided fork has a sample sunrise file with the requisite lines commented out. You can check it out here:

https://github.com/fansided/Mercator/blob/master/sunrise-sample.php
