### ISSUE TITLE
Mercator still supporting?

### ISSUE THREAD

**Issue by LehaMotovilov** [humanmade/Mercator#70]
I like this plugin, but I don't understand @rmccue you're still support this cool extension or not?
Many issues and pull requests without responses.

**Comment by rmccue** [comment]
Mercator is in use in production on quite a few of our sites, and we still support it. I haven't had time to review most of the issues and PRs here, but Mercator is basically feature complete and stable for our usage.

I'll try and get some time in this week to review everything here.
