### ISSUE TITLE
A step by step tutorial: How to get Mercator to work.

### ISSUE THREAD

**Issue by paaljoachim** [humanmade/Mercator#71]
Hi

I have made a step by step tutorial on how to get Mercator to work:
 http://easywebdesigntutorials.com/how-to-point-a-top-level-domain-to-a-multisite-using-domain-mapping/

**Comment by roborourke** [comment]
@paaljoachim thanks! This is great :) I'll add posts & resources like this to the wiki

**Comment by paaljoachim** [comment]
Btw I did a quick scan of the readme.
People come here to download and figure out how to use the plugin, so it would be good for everyone that the tutorial is easy to see.

**Comment by roborourke** [comment]
@paaljoachim I'll get some proper docs up on an upcoming dedicated site that will outline the new ecosystem of Mercator plugins. I'm not sure we'll list specific tutorials in the readme as it should just provide generic information about `sunrise.php` and `wp-config.php` constants needed. It's possibly frustrating I understand but intentionally high level at the moment to avoid the need for providing support we don't have the capacity to provide for our open source plugins.

**Comment by paaljoachim** [comment]
Hey Robert

Gotcha. I understand the high level knowledge required to use it. I do my best to bring that high level knowledge down to a level that most who need to know can figure out how to use the plugin (really any feature in WordPress that I myself am curious about). Often times when people do not figure it out how to use a product they will find some channel to ask questions so they learn how it is done. It is nice to offer basic setup tutorials where one can also mention at the end that additional questions are asked in a specific forum or not supported.

".....upcoming dedicated site that will outline the new ecosystem of Mercator plugins." 
That sounds very interesting! Where can I find more information about the various ecosystem Mercator plugins? It would be great to also on occasion drop by the multisite core channel:  https://wordpress.slack.com/messages/core-multisite/ and mention some of the work being done  as there might be some features you guys are working on that would be natural to add directly to core.
