### ISSUE TITLE
Is this plug-in even necessary or commended?

### ISSUE THREAD

**Issue by jonathannz** [humanmade/Mercator#94]
It's my understanding newer (v4.5+) versions of WP handle custom domains internally. In which case I understood plug-ins such as this are redundant. Is that the case? If it is, would it not be worth mentioning that in the description?

**Comment by mrjarbenne** [comment]
Mapping one custom domain to a URL is supported, with caveats (https://halfelf.org/2014/mapping-domains-without-plugin/). 

If you want multiple domains mapped to the same site, or want to use the unmapped domain for your wp-admin (in cases where you are using a wildcard SSL Cert) or a number of other cases others may have, plugins like this are still relevant and required.

**Comment by roborourke** [comment]
Thanks for the answer @mrjarbenne - @jonathannz in cases you want multiple aliases you would need this plugin or a similar one. The other advantage is still being able to access a site via the initial subdomain it was set up on in instances where the domain expires or hasn't propagated yet for example.
